### ISSUE TITLE
FnDef is not a function pointer

### ISSUE THREAD

**Issue by bjorn3** [sapir/gcc-rust#10]
https://github.com/sapir/gcc-rust/blob/5ea9fadaf646957b73b066ceecd4c661035d586d/gcc/rust/gcc-rust/src/mir2gimple.rs#L181

It is a ZST which specifies a specific function. `a as fn()` casts to `FnPtr` instead.

**Comment by sapir** [comment]
This was because the gcc call_expr needs to get a function pointer, so I wanted Call(an_fndef) to get translated to call_expr(&an_fndef).
Is there a case where doing this causes incorrect codegen?

**Comment by bjorn3** [comment]
> Is there a case where doing this causes incorrect codegen?

For example `A { x: func, y: 0 }` where `struct A<T> { x: T, y: u8 }` and `fn func() {}`. This would cause `y` to be at offset `8` instead of the required `0`. You should instead create a function pointer inside `convert_call_expr`.

Also `convert_call_expr` isn't correct for calls on trait objects. When the `instance` resulting from calling `Instance::resolve(tcx, ParamEnv::reveal_all(), def_id, substs)` (where `def_id` and `substs` are from `FnDef`) is `Instance { def: InstanceDef::Virtual(_, idx), .. }`, you should take a function pointer from the correct place in the vtable from the meta part of the first arg, and discard that meta part when performing the actual call.

For example the `type_id` call of `let a: Box<Any> = Box::new(()); a.type_id()` would get translated to:

```
let f: fn(*const ()) = *(a.meta + (idx + 3) * size_of::<usize>());
f(a.data);
```
