### ISSUE TITLE
Trait objects

### ISSUE THREAD

**Issue by sapir** [sapir/gcc-rust#11]

**Comment by sapir** [comment]
From https://github.com/sapir/gcc-rust/issues/10#issuecomment-569431522:

convert_call_expr isn't correct for calls on trait objects. When the instance resulting from calling Instance::resolve(tcx, ParamEnv::reveal_all(), def_id, substs) (where def_id and substs are from FnDef) is Instance { def: InstanceDef::Virtual(_, idx), .. }, you should take a function pointer from the correct place in the vtable from the meta part of the first arg, and discard that meta part when performing the actual call.

For example the type_id call of let a: Box<Any> = Box::new(()); a.type_id() would get translated to:

let f: fn(*const ()) = *(a.meta + (idx + 3) * size_of::<usize>());
f(a.data);

**Comment by bjorn3** [comment]
I believe 2f54fee0ee5d87338c5ef4cfdaec4b7b87692341 doesn't use `a.data` instead of `a` as first argument for the called function.

**Comment by sapir** [comment]
oops
