### ISSUE TITLE
Maybe use raw bytes instead of full types?

### ISSUE THREAD

**Issue by bjorn3** [sapir/gcc-rust#15]
It is much easier to just use the layout computations of rustc instead of translating every type to a gcc type. This also prevents any mismatches between the rustc computed layout and the layout used by gcc-rust. It is necessary to use the same layout, as const evaluating statics, promoteds and const operands gives raw bytes with any necessary relocations instead of giving a rust value. These raw bytes have the rustc computed layout, so interpreting them as a different gcc calculated layout will be wrong. Also there are several layout optimizations which are guaranteed by rustc/assumed by a lot of code which may be hard to model using C types. For example `Option<&T>` has the same size as `*const T` with `0` as `None`.

**Comment by sapir** [comment]
I do want to use the real layout info, but I thought I'd convert it to a gcc representation. Wouldn't treating everything as bytes (assuming I can get that to work with the gcc typing rules) break optimizations?

**Comment by bjorn3** [comment]
Maybe take the same approach as cg_llvm: derive as much as possible from TyLayout and special case some types.

https://github.com/rust-lang/rust/blob/bc1571cc3cfef07251f7df52b95525aa16797ca2/src/librustc_codegen_llvm/type_of.rs#L14

**Comment by sapir** [comment]
Mostly done in 247ef44aa.

**Comment by bjorn3** [comment]
Did you mean to close #9 instead?

**Comment by bjorn3** [comment]
Just saw the other commits you pushed. One small comment: https://github.com/sapir/gcc-rust/commit/66ef049441d0f96532125bb6a2097189167f24ae#r38596441.

**Comment by sapir** [comment]
> Did you mean to close #9 instead?

I'm keeping that open for now.
