### ISSUE TITLE
What are you using as tests?

### ISSUE THREAD

**Issue by bjorn3** [sapir/gcc-rust#16]
Just curious. Couldn't find it in tree.

**Comment by sapir** [comment]
I'm just manually compiling random bits of code, and then trying to fix the resulting random errors, no real tests.

**Comment by bjorn3** [comment]
Maybe use the tests from https://github.com/bjorn3/rustc_codegen_cranelift/tree/c6086a8fd7489fa6cf18b7dd0baf73cf21386c77/example? The `example.rs` and `mini_core_hello_world.rs` files depend on `mini_core.rs`, the rest requires core, alloc and std. cg_clif is dual licensed as MIT or Apache-2.0. MIT is compatible with GPLv3, so you can just copy them.

**Comment by sapir** [comment]
Thanks!

I set up a test script: https://github.com/sapir/gcc-rust-tests

I still haven't added your tests, though. I'll open an issue in the other repo.
