### ISSUE TITLE
Readme contains uncompilable code

### ISSUE THREAD

**Issue by ArekPiekarz** [sapir/gcc-rust#2]
Readme states that gcc-rust can compile:
`fn my_function(x: i32) { x }`
but rustc fails to do it:
```
error[E0308]: mismatched types
 --> src/lib.rs:1:26
  |
1 | fn my_function(x: i32) { x }
  |                        - ^ expected (), found i32
  |                        |
  |                        help: try adding a return type: `-> i32`
  |
  = note: expected type `()`
             found type `i32`
```
So it should be either
`fn my_function(x: i32) -> i32 { x }`
or
`fn my_function(x: i32) { }`

**Comment by sapir** [comment]
Yes, you're right, of course. The first one is the one that works. I'll fix it after I get home.

The second one actually triggers a gcc crash, I think due to an attempt by gcc-rust to initialize a void value.

**Comment by sapir** [comment]
fixed

**Comment by sapir** [comment]
also I fixed the crash now
