### ISSUE TITLE
Support closures

### ISSUE THREAD

**Issue by sapir** [sapir/gcc-rust#8]

**Comment by bjorn3** [comment]
For the "rust-call" abi you need to unpack the components of the second argument, which is a tuple, and pass each as seperate arguments. If `mir.spread_arg` is `None` for a function with "rust-call" abi, then you are a real closure, and every of those args is already unpacked at the callee side. For example a closure of type `FnOnce(u8, u16)` has a `call_once` signature of `fn(self, (u8, u16))`, but the mir has separate args for each user facing argument. If `mir.spread_arg` is `Some(_)` however the function is actually a manual implementation of a `Fn*` trait. In that case you will need to store all arguments unpacked at the caller site in the local stored in `mir.spread_arg`. cg_clif implements this logic at https://github.com/bjorn3/rustc_codegen_cranelift/blob/7ff01a4d59779609992aad947264abcc64617917/src/abi/mod.rs#L306-L324 and https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/src/abi/mod.rs#L377-L386

**Comment by sapir** [comment]
afaict simple closures work now

I created a new issue for rust-call
